### ISSUE TITLE
Trackplan Data Missing

### ISSUE THREAD

**Issue by anthonymariniello** [torqu3e/speedangle-to-racechrono#2]
Awesome work Tejinder,
I noticed the track plan data doesn't see seem to come across to create the lap/sector information in the conversion I ran. I've attached the input file encase this helps.

[Oakleigh.zip](https://github.com/torqu3e/speedangle-to-racechrono/files/6593014/Oakleigh.zip)

**Comment by torqu3e** [comment]
After importing the file into RCchrono, you will see three circles where the last one says "Select Track". Click that and select Oakleigh Go Kart, sector info will show up.

Separate note, you can also use the online version to convert at https://sa2rc.herokuapp.com/
